default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: survivor_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: survivor_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  <<: *default
  database: survivor_production
  username: postgres
  password: <%= ENV['SURVIVOR_DATABASE_PASSWORD'] %>
