default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: survivors_portal_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: survivors_portal_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  <<: *default
  database: survivors_portal_production
  username: postgres
  password: <%= ENV['SURVIVOR_DATABASE_PASSWORD'] %>
